'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto VS.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("covid.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        '''  ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;en&quot;&gt;
        '''&lt;head&gt;
        '''    &lt;meta charset=&quot;utf-8&quot; /&gt;
        '''    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, shrink-to-fit=no&quot; /&gt;
        '''    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        '''    &lt;title&gt;test&lt;/title&gt;
        '''    &lt;link href=&quot;{0}Content/font-awesome.min.css&quot; rel=&quot;stylesheet&quot; /&gt;
        '''    &lt;style&gt;{1}&lt;/style&gt;
        '''&lt;/head&gt;
        '''&lt;body style=&quot;background-color:lavender&quot;&gt;
        '''    &lt;div id=&quot;svgContainer&quot;&gt;{3}&lt;/div&gt;
        '''    &lt;script src=&quot;{0}Scripts/jquery-3.4.1.min.js&quot;&gt;&lt;/script&gt;
        '''   [stringa troncata]&quot;;.
        '''</summary>
        Friend ReadOnly Property htmlpage() As String
            Get
                Return ResourceManager.GetString("htmlpage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a function test(msg) {
        '''    alert(msg);
        '''}.
        '''</summary>
        Friend ReadOnly Property svgScript() As String
            Get
                Return ResourceManager.GetString("svgScript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a #container {
        '''    height:1600px;
        '''}
        '''
        '''svg {
        ''' }
        '''
        '''.sfondo {
        '''    fill: #d7dff0   ;
        '''    stroke:gray;
        '''    stroke-width:2;
        '''}
        '''
        '''.rigaGiorno {
        '''    stroke: gray;
        '''    stroke-width: 1;
        '''    opacity:.5
        '''}
        '''
        '''.rigaMese {
        '''    stroke: black;
        '''    stroke-width: 1;
        '''    opacity: .8
        '''}
        '''
        '''.testoGiorno {
        '''    font-weight:300;
        '''    font: 12px verdana;
        '''    stroke: navy;
        '''    text-anchor :middle;
        '''    opacity:.6;
        '''}
        '''
        '''.testoMese {
        '''    font-weight: 300;
        '''    font: 18px verdana;
        '''    stroke: navy;
        '''    text-anchor:  [stringa troncata]&quot;;.
        '''</summary>
        Friend ReadOnly Property svgstyle() As String
            Get
                Return ResourceManager.GetString("svgstyle", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
